name: First Workflow
on: 
  push:

jobs: 
  show_date:
    runs-on: ubuntu-latest
    steps:
    - name: show date
      run: echo "The current date is $(date)"
    - name: show current branch
      run: echo ${{github.ref_name}}

  test_and_deploy:
    runs-on: ubuntu-latest
    env:
      OPENWEATHERMAP_KEY: ${{secrets.openweathermap_api}}
    steps:
    - name: setup JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: setup maven
      uses: stCarolas/setup-maven@v4.3
      with:
        maven-version: 3.8.2

    - name: checkout the source
      uses: actions/checkout@v3

    - name: run test
      run: mvn clean test

    - name: deploy to heroku
      uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: ${{secrets.appname}}
        heroku_email: ${{secrets.appemail}}
        branch: ${{github.ref_name}}