name: First Workflow
on: 
  push:
jobs: 
  show_date:
    runs-on: ubuntu-latest
    steps:
    - name: show date
      run: echo "The current date is $(date)"
    - name: simulate a fail
      run: exit 1
    - name: show current branch
      run: echo ${{github.ref_name}}